# Generated by Django 5.1.4 on 2025-01-08 19:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_order_is_active_order_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="extras",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), blank=True, default=list, size=None
            ),
        ),
    ]
