# Generated by Django 5.1.4 on 2025-01-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_orderitem_extras"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="extras",
            field=models.JSONField(),
        ),
    ]
