# Generated by Django 5.1.4 on 2025-01-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_orderitem_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="special_requests",
            field=models.TextField(blank=True, null=True),
        ),
    ]
